jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_USER}
        password: ${JENKINS_ADMIN_PASS}
  authorizationStrategy: loggedInUsersCanDoAnything

